##  Importing Libraries

I start by importing the necessary library, **pandas**, which is used for data manipulation and analysis.

In [1]:
import pandas as pd

## Part 1: Creating My Own Dataset

I create a dataset of 15 students with 5 features: **Name, Age, Gender, Score, Passed**.  
I organize the data using a **dictionary** in Python.

In [2]:
data = {
    "Name": ["Alem", "Beti", "Chala", "Dawit", "Eden", "Fikir", "Gashaw", "Hana", "Israel", "Jemal",
             "Kebede", "Liya", "Marta", "Nati", "Omer"],
    "Age": [21, 22, 23, 24, 20, 25, 26, 22, 23, 24, 27, 21, 22, 23, 24],
    "Gender": ["F", "F", "M", "M", "F", "F", "M", "F", "M", "M", "M", "F", "F", "M", "M"],
    "Score": [85, 90, 78, 88, 92, 95, 70, 89, 76, 84, 73, 91, 87, 80, 82],
    "Passed": ["Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "Yes", "Yes", "Yes"]
}

## Custom Index for My Dataset

I assign a custom index to my dataset rows using numbers 101 to 115

In [3]:
index_numbers = [i for i in range(101, 116)]

## Creating DataFrame with Custom Index

Now I create the DataFrame using my data and the custom index

In [4]:
df = pd.DataFrame(data, index=index_numbers)

## Displaying the DataFrame

To see the DataFrame I created

In [5]:
df

       Name  Age Gender  Score Passed
101    Alem   21      F     85    Yes
102    Beti   22      F     90    Yes
103   Chala   23      M     78    Yes
104   Dawit   24      M     88    Yes
105    Eden   20      F     92    Yes
106   Fikir   25      F     95    Yes
107  Gashaw   26      M     70     No
108    Hana   22      F     89    Yes
109  Israel   23      M     76     No
110   Jemal   24      M     84    Yes
111  Kebede   27      M     73     No
112    Liya   21      F     91    Yes
113   Marta   22      F     87    Yes
114    Nati   23      M     80    Yes
115    Omer   24      M     82    Yes

## Importing Libraries

I start by importing the necessary library, **pandas**

In [6]:
import pandas as pd

### Load Titanic Dataset
Load the Titanic dataset into a pandas DataFrame using `pd.read_csv`.  
The dataset contains passenger details such as age, gender, class, fare, and survival status.

In [7]:
titanic = pd.read_csv("/kaggle/input/datasets/lidiakibret/titanic-analysis/train.csv")

### Preview Titanic Dataset
Display the first 5 rows of the Titanic dataset to inspect the structure and sample data.

In [8]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Titanic Dataset Information
Check the structure of the dataset, including column names, data types, and non-null counts.

In [9]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Titanic Dataset Summary Statistics
Get an overview of the numeric columns including count, mean, standard deviation, min, max, and quartiles.

In [10]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Titanic Dataset — Data Cleaning
Handle missing values and remove unnecessary columns and duplicates.

In [11]:
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].median())
titanic['Embarked'] = titanic['Embarked'].fillna(titanic['Embarked'].mode()[0])
titanic = titanic.drop(columns=['Cabin'], errors='ignore')
titanic = titanic.drop_duplicates()

titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

### Survival Rate by Gender

This step calculates the **survival rate for each gender** in the Titanic dataset:

- The dataset is grouped by the `Sex` column.  
- For each gender group, the mean of the `Survived` column is calculated.  
- The resulting values represent the **proportion of passengers who survived** in each gender group, helping to identify which gender was more likely to survive.

In [12]:
survival_gender = titanic.groupby('Sex')['Survived'].mean()
survival_gender

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

### Survival Rate by Passenger Class

This step calculates the **survival rate for each passenger class**:

- The dataset is grouped by the `Pclass` column (1st, 2nd, 3rd class).  
- For each class, the mean of the `Survived` column is computed.  
- The resulting values indicate the **proportion of passengers who survived in each class**, showing how class affected survival chances.

In [13]:
survival_class = titanic.groupby('Pclass')['Survived'].mean()
survival_class

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

### Average Age per Passenger Class

This step calculates the **average age of passengers in each class**:

- The dataset is grouped by the `Pclass` column (1st, 2nd, 3rd class).  
- For each class, the mean of the `Age` column is computed.  
- The result shows the **typical age of passengers in each class**, helping to understand age distribution across classes.

In [14]:
avg_age_class = titanic.groupby('Pclass')['Age'].mean()
avg_age_class

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

### Survival Rate by Age Group

This step categorizes passengers into **age groups** and calculates their survival rates:

1. **Age Grouping**:
   - `0-12` → Child  
   - `13-18` → Teen  
   - `19-35` → Young Adult  
   - `36-60` → Adult  
   - `61-100` → Senior  
   - `pd.cut` is used to assign each passenger to an age group.  

2. **Survival Calculation**:
   - The dataset is grouped by the `AgeGroup` column.  
   - For each group, the mean of the `Survived` column is computed.  
   - The result shows the **likelihood of survival for each age group**, indicating which ages were prioritized during evacuation.

In [15]:
bins = [0, 12, 18, 35, 60, 100]
labels = ['Child','Teen','Young Adult','Adult','Senior']
titanic['AgeGroup'] = pd.cut(titanic['Age'], bins=bins, labels=labels)

survival_age_group = titanic.groupby('AgeGroup', observed=True)['Survived'].mean()
survival_age_group

AgeGroup
Child          0.579710
Teen           0.428571
Young Adult    0.353271
Adult          0.400000
Senior         0.227273
Name: Survived, dtype: float64

### Female Passengers Who Survived

This step filters the dataset to identify **female passengers who survived**:

- The condition `(titanic['Sex']=='female')` selects all female passengers.  
- The condition `(titanic['Survived']==1)` selects those who survived.  
- Combining both conditions with `&` results in a **subset of female survivors**.  

This helps in analyzing **gender-based survival patterns** and confirms that females had higher survival rates compared to males.

In [16]:
female_survived = titanic[(titanic['Sex']=='female') & (titanic['Survived']==1)]
female_survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Young Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Young Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Young Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C,Young Adult
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,Teen
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S,Young Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Young Adult

### Children Who Survived

This step filters the dataset to identify **child passengers who survived**:

- The condition `(titanic['Age'] <= 12)` selects all passengers aged 12 or below.  
- The condition `(titanic['Survived']==1)` selects those who survived.  
- Combining both conditions with `&` results in a **subset of children who survived**.  

This analysis helps determine if **children were prioritized for survival** during the Titanic disaster.

In [17]:
children_survived = titanic[(titanic['Age'] <= 12) & (titanic['Survived']==1)]
children_survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,Child
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,C,Child
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,S,Child
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,Child
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,C,Child
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,Child
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,S,Child
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,Child
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,S,Child
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,Child
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,S,Child
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,S,Child
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,Child
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,Child
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,Child
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,Child
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,C,Child
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,Child
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,Child
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,C,Child
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,C,Child
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,S,Child
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,Child
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,S,Child
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,S,Child
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,Child
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,S,Child
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,C,Child
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,C,Child
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,S,Child
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,S,Child
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,Child
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,Child
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,S,Child
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,Child
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,S,Child
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,Child
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,Child
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,Child
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,Child

### First-Class Passengers Who Survived

This step filters the dataset to find **first-class passengers who survived**:

- The condition `(titanic['Pclass']==1)` selects passengers in **1st class**.  
- The condition `(titanic['Survived']==1)` selects passengers who **survived**.  
- Combining both conditions with `&` results in a **subset of first-class survivors**.  

This helps analyze whether **passenger class affected survival probability**.

In [18]:
first_class_survived = titanic[(titanic['Pclass']==1) & (titanic['Survived']==1)]
first_class_survived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Young Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Young Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Young Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Adult
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Adult
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Young Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Young Adult

### Gender Most Likely to Survive

This step identifies **which gender had the highest survival rate**:

- `survival_gender` contains the **average survival rate** for each gender.  
- `idxmax()` returns the **index (gender)** corresponding to the **highest survival rate**.  

Result shows **females were more likely to survive** than males.

In [19]:
most_likely_gender = survival_gender.idxmax()
most_likely_gender

'female'

### Passenger Class with Highest Survival Rate

This step determines **which passenger class had the highest chance of survival**:

- `survival_class` calculates the **average survival rate for each Pclass**.  
- `idxmax()` identifies the **class with the maximum survival rate**.  

Result indicates that **1st class passengers had the highest survival rate**.

In [20]:
survival_class = titanic.groupby('Pclass')['Survived'].mean()
best_class = survival_class.idxmax()
best_class

np.int64(1)

### Survival Rate of Children

This step calculates the **survival rate specifically for children**:

- `survival_age_group` contains survival rates for all age groups.  
- Accessing `['Child']` gives the **proportion of children who survived**.

Result shows that **children had a higher survival rate compared to most other age groups**.

In [21]:
child_survival_rate = survival_age_group['Child']
child_survival_rate

np.float64(0.5797101449275363)

### Highest Survival Combination by Gender and Class

This step identifies which **gender and passenger class combination had the highest survival rate**:

- `groupby(['Sex','Pclass'])['Survived'].mean()` calculates the average survival rate for each combination of gender and class.  
- `.idxmax()` returns the combination with the **highest survival probability**.

The output shows the **most advantaged group on the Titanic in terms of survival**.

In [22]:
highest_combination = titanic.groupby(['Sex','Pclass'])['Survived'].mean().idxmax()
highest_combination

('female', np.int64(1))